version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.1.4-20220427
    shm_size: 2gb
    container_name: chrome
    depends_on:
      - seleniumhub
    environment:
      - SE_EVENT_BUS_HOST=seleniumhub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  seleniumhub:
    image: selenium/hub
    container_name: seleniumhub
    ports:
      - "4444:4444"
  uitests:
    build: .
    container_name: uitests
    ports:
      - "4447:4447"
    depends_on:
      - seleniumhub
    volumes:
      - .:/tests